---
- name: Create directory for monitoring
  file:
    path: "{{ monitoring_installation_path }}"
    state: directory
    mode: 0755

- name: Generate node exporter compose file
  template:
    src: ../templates/node-exporter-compose.j2
    dest: "{{ monitoring_installation_path }}/node-exporter-compose.yml"
    owner: root
    group: root
    mode: 0755
  notify: Start node exporter compose file
  register: node_exporter_compose_file
  when: "inventory_hostname not in groups['monitorings']"

- name: Generate Prometheus config file
  template:
    src: ../templates/prometheus-config.j2
    dest: "{{ monitoring_installation_path }}/{{prometheus_config}}"
    owner: root
    group: root
    mode: 0755
  when: "inventory_hostname in groups['monitorings']"

- name: Generate monitoring compose file
  template:
    src: ../templates/monitoring-compose.j2
    dest: "{{ monitoring_installation_path }}/monitoring-compose.yml"
    owner: root
    group: root
    mode: 0755
  register: monitoring_compose_file
  notify: Start monitoring compose file
  when: "inventory_hostname in groups['monitorings']"