---
- name: Generate Broker config file
  template:
    src: ../templates/broker-conf.j2
    dest: "{{ pinot_installation_path }}/broker.conf"
    owner: root
    group: root
    mode: 0755

- name: Generate Broker compose file
  template:
    src: ../templates/broker-compose.j2
    dest: "{{ pinot_installation_path }}/broker-compose.yml"
    owner: root
    group: root
    mode: 0755
  register: broker_compose_file
  notify: Start broker compose file