

- name: Delete all containers
  shell:
    cmd: "docker rm -f $(docker ps -aqs) || true" 

- name: Delete created directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ pinot_installation_path }}"
    - "{{ monitoring_installation_path }}"


