---
- name: Start monitoring compose file
  shell:
    cmd: "docker compose -f {{ monitoring_compose_file.dest }} up -d"

- name: Start node exporter compose file
  shell:
    cmd: "docker compose -f {{ node_exporter_compose_file.dest }} up -d"